"""@package Problem
    
    Project Eular - Problem 45

    Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

    Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
    Pentagonal  Pn=n(3n-1)/2  1, 5, 12, 22, 35, ...
    Hexagonal   Hn=n(2n-1)    1, 6, 15, 28, 45, ...
    
    It can be verified that T285 = P165 = H143 = 40755.

    Find the next triangle number that is also pentagonal and hexagonal.
    
    @author Shane Auckland <shane.auckland@gmail.com>
    
"""
import math

def isPentagonal(n):
    return testNumber(n, 24, 6)

def isHexagonal(n):
    return testNumber(n, 8, 4)

def testNumber(n, a, b):
    result = (math.sqrt((a*n)+1) + 1) / b
    return result % 1 == 0

t = 286

while True:
    tri = (t*(t+1))/2
    if isHexagonal(tri) and isPentagonal(tri):
        break
    t += 1

print t, tri

